### ISSUE TITLE
Recursively Formatting

### ISSUE THREAD

**Issue by d-pizhuk** [google/google-java-format#1030]
Is it possible to format files in a folder recursively? 
I tried: java -jar google-java-format-1.19.2-all-deps.jar -replace  "folder/extra/*", but it formats only files within this folder and does not format files in inner folders.

**Comment by cushon** [comment]
There isn't built-in functionality for walking a folder to find files to format. On unix you could consider something like:

```
find folder/extra/ -type f -name '*.java' | xargs google-java-format -i
```

**Comment by mihnita** [comment]
If I implement this functionality and create a PR would you consider taking it?

I am working on a project with thousands of Java files in hundreds of folders.
And some devs work on Windows, so `find` and `xargs` are not available to all.

Even a trivial one (without fancy include / exclude patterns for files / folders) would be nice.
(although I am considering doing all of that, maybe in stages, first basic recursivity, then make if fancier)

Thank you very much,
Mihai

**Comment by mihnita** [comment]
Note: I don't expect an unconditional _"yes"_, as in _"we take it, even if it is crap"_. Of course.
But to at least know that I don't spend time working on this only to get a _"no, this is a feature we don't want, sorry you wasted your time"_

**Comment by mihnita** [comment]
Thank you for the quick answer.
Fair enough :-)

**Comment by jpstotz** [comment]
That google-java-format doesn't have a recursive option is really sad and makes it more or less useless to me as I prefer to use simple easy to use self-contained tools. 

Also a recursive option would be much faster instead of having to use platform/shell dependent shell magic to execute google-java-format for each and every source file. Thus I would call the current approach heavily inefficient. This also applies to shell/python/whatever wrapper scripts.

So having one recursive option that works the same way on all operating systems would be IMHO a great benefit.
