### ISSUE TITLE
Is possible to turn of wildcard import rule?

### ISSUE THREAD

**Issue by poliveira-fuze** [google/google-java-format#1154]
Or even allow to to something "AvoidStarImport" or "AvoidWildcardImport"

**Comment by tbroyer** [comment]
Not sure I understand what you're asking but Google Java Format can only remove unused imports or reorder them, it cannot "expand" wildcard imports, because [_it's not a compiler_](https://github.com/google/google-java-format/wiki/FAQ#what-do-you-mean-its-not-a-compiler)

You can use Error Prone though with its (disabled by default) [`WildcardImport` rule](https://errorprone.info/bugpattern/WildcardImport), and probably other tools, to fail your build if sources contain a wildcard import. But you'll need an IDE to expand the wildcard.

**Comment by poliveira-fuze** [comment]
I did not understood
> You can use Error Prone though with its (...)

Aside that rule webpage, what ErrorProne can do?

And if it's disabled how can I enable it?

**Comment by poliveira-fuze** [comment]
From what I read, ErrorProne does not change anything. Just point out on the compilation.
