### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by daksunt** [google/google-java-format#121]
There is an exception when running

`String formattedSource = new Formatter().formatSource(sourceString);`

> Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.Range.closedOpen(Ljava/lang/Comparable;Ljava/lang/Comparable;)Lcom/google/common/collect/Range;
	at com.google.googlejavaformat.java.Formatter.<clinit>(Formatter.java:92)

**Comment by jbduncan** [comment]
Hi @daksunt. From the information you've given us so far, I'd suspect it's because `google-java-format` is trying to use a version of Guava that doesn't have `Range.closedOpen()`, but it's not clear to me why that's the case yet. 

Could you tell us which version of `google-java-format` you're using, as well as how you're using it?

**Comment by sormuras** [comment]
I guess, it's due to a Guava library pre 14.0 in the class path: https://google.github.io/guava/releases/21.0/api/docs/com/google/common/collect/Range.html#closedOpen-C-C-

**Comment by jbduncan** [comment]
Yes, you're probably right @sormuras.

@daksunt, are you by any chance using `google-java-format-1.x.jar` rather than `google-java-format-1.x-all-deps.jar`?

**Comment by daksunt** [comment]
It seems that I am using google-java-format-1.2.jar, with all deps it works. Thanks @jbduncan .

**Comment by jbduncan** [comment]
Hi @daksunt, I'm glad to hear. :)

Does this resolve your issue for now? If so, would you kindly close this issue for now?
