### ISSUE TITLE
Unable to set AOSP style in IDEA plugin

### ISSUE THREAD

**Issue by gavinsherry** [google/google-java-format#136]
I'd love to use the IntelliJ plugin but I need to use it with code that conforms to the AOSP style guide. I couldn't see how to toggle the style in the IntelliJ plugin despite support in the core module. Am I missing something?

**Comment by markiewb** [comment]
At least in the 1.2-SN version it can be set. I did not try 1.0
![2017-03-16_21h37_44](https://cloud.githubusercontent.com/assets/1857095/24017570/dee3c922-0a90-11e7-93c1-ce25dd441bfc.png)

**Comment by gavinsherry** [comment]
Hi @markiewb. I'm not sure what `1.2-SN` is. I'm using IntelliJ `2016.3.5`.

**Comment by markiewb** [comment]
Rollback. It is not compatible yet to 2016.3+.
https://github.com/google/google-java-format/issues/115

Den 21 mars 2017 04:08 skrev "Gavin Sherry" <notifications@github.com>:

**Comment by markiewb** [comment]
At http://plugins.jetbrains.com/plugin/8527-google-java-format you will
find the other version, but as stated before. It won't start on 2016.3
unless you edit the plugin.xml

Den 21 mars 2017 04:08 skrev "Gavin Sherry" <notifications@github.com>:

Hi @markiewb <https://github.com/markiewb>. I'm not sure what 1.2-SN is.
I'm using IntelliJ 2016.3.5.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/google/google-java-format/issues/136#issuecomment-287963819>,
or mute the thread

**Comment by gavinsherry** [comment]
I see. Thanks @markiewb. When will a `2016.3.15` build be available?

**Comment by markiewb** [comment]
That is a question for the plugin author.

Den 22 mars 2017 17:51 skrev "Gavin Sherry" <notifications@github.com>:

**Comment by cushon** [comment]
This is a duplicate of #115
