### ISSUE TITLE
permitted end-of-class vertical whitespace is deleted

### ISSUE THREAD

**Issue by novalis** [google/google-java-format#157]
https://google.github.io/styleguide/javaguide.html#s4.6.1-vertical-whitespace permits a newline both after class { and before the trailing } of the class.  e.g.
```
class Fleem {

  int morx() {
    return 5;
  }

}
```
But google-java-format will delete the newline before the final } (though not the initial one).

**Comment by kevinb9n** [comment]
This is actually intended behavior; google-java-format doesn't just fix violations, it chooses a formatting for your file, with the goal of consistency.

**Comment by novalis** [comment]
Then why doesn't it do it for the initial newline too?

**Comment by kevinb9n** [comment]
(So in general it ignores existing formatting choices, but we have a short list of specific exceptions when it's justified. There was an argument why the blank line after the opening brace makes sense to preserve (I think because that choice may depend on just how dense and ugly the line after it is), which didn't seem to apply in this case at all.)
