### ISSUE TITLE
Tag released IntelliJ versions

### ISSUE THREAD

**Issue by mastersimon** [google/google-java-format#180]
Is it possible that you tag the branch for the released IntelliJ versions?

**Comment by plumpy** [comment]
I make the IntelliJ plugins with the latest version of the IntelliJ plugin code and the latest _released_ version of the google-java-format code (so, 1.3 currently). So there's not really a single commit I could tag, unfortunately...

**Comment by mastersimon** [comment]
The tag `google-java-format-1.3` has been created at 02/10/2017. The IntelliJ plugin version `1.3.2` has been released on 08/02/2017.

**Comment by plumpy** [comment]
Right, so what I did was took the google-java-format-1.3.jar and built the IntelliJ plugin using that jar along with the IntelliJ classes from 511b978. I suppose I could tag 511b978 as intellij-plugin-1.3.2, but it would probably be confusing, since that only really applies to the IntelliJ classes, not the formatter code.

So you won't get any _formatter_ bugfixes that have been checked in since February, you'll only get fixes to the IntelliJ code. Does that make sense? So I'm not sure how to do what you're asking in a sensible way. Maybe I could just document what I did in the plugin release notes?

**Comment by mastersimon** [comment]
Okay, I do understand the problematic you are describing. 

I guess it is a good idea to document at least the point of time (e.g. commit id) where the new IntelliJ version has been created.

**Comment by plumpy** [comment]
I uploaded new versions of the plugin and added this to the plugin description: "This version of the plugin uses google-java-format 1.4."

I think that's about the best I can do for now. I don't build the plugins out of github, I build them out of Google's internal source repository, so I think that's about all I can do. Thanks!
