### ISSUE TITLE
Gap between 1.4.0.162 and 1.4.0.171

### ISSUE THREAD

**Issue by mkillianey** [google/google-java-format#189]
The range declared in 1.4.0.162 is:
`<idea-version since-build="162" until-build="162.*"/>`
The range declared in 1.4.0.171 is:
`<idea-version since-build="171" until-build="171.*"/>`
This means that there's no version that supports IntelliJ 2016.3.  :-(

I suspect that 1.4.0.162 was supposed to be:
`<idea-version since-build="162" until-build="171"/>`

Could you perhaps release a 1.4.0.163, just changing the until-build line so that 2016.3 users can enjoy the plugin?

**Comment by plumpy** [comment]
Unfortunately, the plugin has to change with every version of IntelliJ, so it's unlikely that the 2016.2 version would work perfectly with 2016.3. We're using some unsupported hacks, so it's more sensitive to version changes than most plugins are.

I removed support for 2016.3 because we no longer support that version inside Google and I figured external users would generally keep up to date with the newest version. (We still support 2016.2 because that's what Android Studio 2.3 is based on.) Is there a reason you don't want to or can't upgrade to 2017.1 or 2017.2? I can see about uploading a 2016.3-compatible version, but I'm genuinely curious why you still want to use that version?

**Comment by plumpy** [comment]
Okay, I uploaded a version for 2016.3. As mentioned, keeping these up to date is a bit of work, so it's unlikely I'll make a 2016.3 plugin for new versions of google-java-format, but let me know if you have any issues installing this version.

**Comment by mkillianey** [comment]
@plumpy  - Thanks for updating, and I totally understand not wanting to fork even more versions.  I'm hoping that when you release the next version, rather than making separate 162/163 versions, maybe you can just make a single 162/163 version by setting the upper bound for that plugin to "163.*"?

**Comment by plumpy** [comment]
Honestly, unless there's a google-java-format 1.5 release in the next month or two, this will probably be the last version of the plugin I upload for versions of the IDE older than 2017.1.
