### ISSUE TITLE
Request supporting apt

### ISSUE THREAD

**Issue by winteryoung** [google/google-java-format#231]
Is there a plan to support `apt install`?

**Comment by winteryoung** [comment]
We need to write a wrapper script to launch this jar and package them both into a .deb file. The wrapper goes to /usr/bin, the jar goes to /usr/lib.

**Comment by winteryoung** [comment]
There's already a google-java-format wrapper for homebrew (mac) and a wrapper for scoop (windows).

**Comment by jbduncan** [comment]
Cool, I wasn't aware that google-java-format is already packaged for homebrew.

If this issue is accepted by the google-java-format team, I wonder (on a sort of side note) if [chocolatey](https://chocolatey.org/) (Windows) should have a package for google-java-format as well, if it doesn't have one already.

**Comment by cushon** [comment]
This is probably not something we're going to get to ourselves, but if someone wants to package it for `apt` we'd be happy to add a link to https://github.com/google/google-java-format#third-party-integrations.
