### ISSUE TITLE
Two issues with removal of unnecessary import

### ISSUE THREAD

**Issue by Stephan202** [google/google-java-format#240]
Consider the following code:
```java
package com.example;

import com.example.Element;
import java.util.List;

interface MyService {
    void someMethod();

    /** Lists all known {@link Element}s. */
    List<Element> getAllElements();
}
```

Formatting this file with `--aosp` yields:
```java
package com.example;

import java.util.List;

interface MyService {
    void someMethod();

  /** Lists all known {@link com.example.Element}s. */
  List<Element> getAllElements();
}
```

The formatter is correct to remove the `com.example.Element` import, but:
* It isn't necessary to make the `@link`-ed type fully qualified.
* The AOSP indentation multiplier isn't applied to the modified method.

**Comment by cushon** [comment]
> It isn't necessary to make the `@link`-ed type fully qualified.

Because `com.example.Element` is declared in the current package, right? Or would you prefer that the formatter didn't qualify javadoc `@link`s in general?

> The AOSP indentation multiplier isn't applied to the modified method.

The configuration isn't getting plumbed through here: https://github.com/google/google-java-format/blob/9028b42c03d7cff60e995182c2890a20855f6b3b/core/src/main/java/com/google/googlejavaformat/java/RemoveUnusedImports.java#L356-358

**Comment by Stephan202** [comment]
> Because `com.example.Element` is declared in the current package, right?

Yep :). I'm otherwise okay with the formatter qualifying `@link`s.

**Comment by cushon** [comment]
This works now:

```
$ google-java-format -aosp X.java
package com.example;

import java.util.List;

interface MyService {
    void someMethod();

    /** Lists all known {@link Element}s. */
    List<Element> getAllElements();
}
```
