### ISSUE TITLE
Output doesn't match the one in google/styleguide

### ISSUE THREAD

**Issue by mathsalmi** [google/google-java-format#29]
Hi! I saw that the output generated by this program is different than the one generated by Eclipse formatter when I'm using this profile file (https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml).

I want to apologize in advance if I'm wrong but it's just that I got the impression that the outputs should be equal.

Thanks.

**Comment by yaojingguo** [comment]
@kevinb9n So if I want to conform to [Google Java Style](https://google.github.io/styleguide/javaguide.html). I should use [google-java-format](https://github.com/google/google-java-format) instead of [eclipse-java-google-style.xml](https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml). Right?

**Comment by jbduncan** [comment]
@yaojingguo I can't truly speak for @kevinb9n, but I'm sure he'd say something like, "Yes." :)

eclipse-java-google-style.xml is there to help you write _semi_-consistent code whilst typing it up in your IDE, whereas google-java-format is there to iron out the rest of the wrinkles when you're ready to save your source file and commit it to Git (or upload it to your preferred VCS).

**Comment by yaojingguo** [comment]
@jbduncan thanks

**Comment by jbduncan** [comment]
@yaojingguo Well, now that I think about it, just using eclipse-java-google-style.xml and google-java-format is not a guaranteed way of conforming to Google Java Style, because Google Java Style contains non-formatting rules that google-java-format cannot enforce, e.g. [6.2 Caught exceptions: not ignored](https://google.github.io/styleguide/javaguide.html#s6.2-caught-exceptions).

**Comment by yaojingguo** [comment]
@jbduncan thanks for pointing it out
