### ISSUE TITLE
google-java-format import sorting for AOSP

### ISSUE THREAD

**Issue by ngzhian** [google/google-java-format#319]
google-java-format supports the `--aosp` flag, which formats 4 spaces (instead of the default 2 spaces). [AOSP style guide](https://source.android.com/setup/contribute/code-style#order-import-statements) recommends a AOSP specific way to sort imports. If the team open to contribution to extend ImportOrderer to support AOSP sort order as well?
- no new flags will be needed, the existing `--aosp` flag will trigger the AOSP import order
- current AOSP projects don't need to use `--skip-sorting-imports`

**Comment by Stephan202** [comment]
In our team we use `--aosp` for its four spaces, but prefer the "default" import ordering. (Our code base consists mostly of regular Java backend code.) So although the Google team prefers to minimize configurability, I'd like to ask that if this proposal is accepted, there'll be some way to retain the current behavior. :pray:

**Comment by ngzhian** [comment]
That makes sense, i guess a flag like `--aosp-sort-order` would be needed, thanks for voicing this out!

**Comment by eaftan** [comment]
A heads-up that I implemented this (it'll get pushed out in a day or two) but did not add a separate flag.  You can read about our policy toward additional configuration here: https://github.com/google/google-java-format/wiki/FAQ#i-just-need-to-configure-it-a-bit-differently-how

**Comment by novalis** [comment]
Would a flag like --google-import-order=false be rejected because g-j-f is opposed to configuration?  We have the same problem as @Stephan202 has: we have been using google-java-format for years with -a, and we do not want to rearrange all of our imports, but we do want to upgrade. It seems like backwards compatibility would be worth breaking the "no configuration" rule.
