### ISSUE TITLE
Intellij XML Formatter is not in sync with the Plugin

### ISSUE THREAD

**Issue by mehwhatever** [google/google-java-format#356]
The Intellij XML codestyle, found [here](https://raw.githubusercontent.com/google/styleguide/gh-pages/intellij-java-google-style.xml), is not in sync with the Plugin.

For our case the codestyle doesn't break the line at 100, causing LineLength to break.

Either  I need to bring the two in sync, or need to the change the checkstyle for the google found from here: https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml

**Comment by plumpy** [comment]
There's no way to get the XML and google-java-format completely in sync. The options in the IntelliJ Code Style settings simply aren't sufficient to describe all the formatting that Google Java Format does.

I might not understand what you're trying to accomplish, though. Can you explain?

**Comment by mehwhatever** [comment]
The issue is I am trying to use this checkstyle, https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml, however all members on my team do not prefer to have 2 space indent, so we modified the checkstyle and intellij xml to have 4 spaces. 

However on formatting with the XML, the checkstyle doesn't pass.

**Comment by jbduncan** [comment]
@mehwhatever I can't speak for @plumpy or Google, but I think the closest you can get to what you want is to use the google-java-format IntelliJ plugin (which is different to the IntelliJ XML file) together a code formatting and checking plugin with support for google-java-format such as [Spotless](https://github.com/diffplug/spotless).

I think this because even if you were to use Checkstyle's google_checks XML with the google-java-format IntelliJ plugin (which is what I'd recommend otherwise), you'd find that they don't agree all the time because google-java-format and Checkstyle interpret the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html) differently.

I hope this helps. :)

**Comment by plumpy** [comment]
Yeah, using google-java-format is going to get you the best results and will make sure your code passes that checkstyle. That's what this github repository is for.

The code style XML file you reference isn't really related to google-java-format, so please file bugs about it to that repository instead.

Please reopen if I'm misunderstanding you, however.
