### ISSUE TITLE
IntelliJ Plugin - Formatting non-Java files

### ISSUE THREAD

**Issue by seadub** [google/google-java-format#363]
IntelliJ Version 2018.3
google-java-format IntelliJ Plugin version 1.7.0.1

Trying to isolate code formatting changes to Java classes. The indentation seems to impact *all* files, including XML, YAML, and more.

Can we isolate this configuration to _only_ Java files?

**Comment by plumpy** [comment]
google-java-format doesn't have any idea how to format XML, YAML, or any other files, so there's no way it could be doing that. You must be using IntelliJ's built-in code formatter for those. Can you better describe what you're doing and what's happening that you don't expect?

**Comment by seadub** [comment]
The built-in formatter is being used, this may be more of an issue with using the recommended configuration file for import ordering found on the readme:

https://raw.githubusercontent.com/google/styleguide/gh-pages/intellij-java-google-style.xml

I've reviewed the impacted file type configurations, and can isolate this to the following after comparing manually with IntelliJ's "Default" IDE settings:
JavaScript
JSON
TypeScript
XML
Other File Types

**Comment by plumpy** [comment]
Ah, yeah, I see what you're saying. The important thing is to modify your Settings→Editor→Code Style→Java→Import Layout to look like this:
https://ibb.co/Q84XFdG

The rest of that file unimportant, and telling people to import the entire thing is definitely not ideal. I'll see if I can think of something better.

**Comment by tbroyer** [comment]
@plumpy Wouldn't you also want to set the threshold for star imports to a high enough value that it won't ever be reached, and possibly also empty the list of packages to always star-import? (from memory, don't have my IntelliJ at hand right now)

**Comment by jbduncan** [comment]
@seadub I don't think anybody has raised this yet, but the google-java-format plugin for IntelliJ is actually different to the XML file that you linked in your most recent message.

The XML file is used to configure IntelliJ's built-in formatter; comparatively the plugin delegates to google-java-format, which is a separate project that Googlers started because IntelliJ's formatter isn't quite powerful enough to allow code to be formatted according to the Google Java Style Guide - the XML file is just an approximation. :)

**Comment by plumpy** [comment]
@seadub was referencing the instructions, however, which do tell you to import that XML file. This is because google-java-format isn't fully capable of managing your imports. (For example, the style guide forbids wildcard imports, but since google-java-format only knows about a single file at a time, it can't resolve wildcard imports into fully-qualified imports.)

And yes, as @tbroyer mentioned, if you don't import the file, you also need to set the import counts to 999 (thanks for the reminder!):
https://ibb.co/qkhxqym

**Comment by seadub** [comment]
@jbduncan I did notice that distinction after @plumpy provided some feedback.
I am hoping that we can modify the linked file to adjust this configuration to base off of the default IntelliJ format profile, and only impact Java code formatting. I will spend some time reviewing this configuration and see about creating a PR if that file is managed in the project anywhere.

**Comment by seadub** [comment]
PR here: https://github.com/google/styleguide/pull/447
