### ISSUE TITLE
Support foundation javac

### ISSUE THREAD

**Issue by sormuras** [google/google-java-format#387]
Is it possible to abstract the underlying compiler to allow usage of provided `javac` tool?

It would enable supporting new Java syntax (like Text Blocks et al.) out of the box, wouldn't it?

Related issues:
- #340 `switch`-expressions as a preview since Java 12
- #382 `"""Text Blocks"""` as a preview since Java 13-ea

**Comment by cushon** [comment]
The implementation uses internal APIs from the `jdk.compiler` module, not just the public `java.compiler` ones, so using the implementation from the host JDK would require passing additional flags to disable module access checks. It would also mean the formatter had to support a range of versions of the internal APIs, which is difficult because there can be breaking changes between releases.

Also, this would only solve half of the problem for new language features: having a parser that handles switch expressions and text blocks isn't sufficient, the formatting logic still has to be updated to decide what to do with those constructs.

**Comment by eaftan** [comment]
Closing as Infeasible

**Comment by cushon** [comment]
After thinking about this more, it may be part of the solution after all. Let's continue the discussion in #436.
