### ISSUE TITLE
Intellij plugin seems to stop working when Java 14/15 features are used

### ISSUE THREAD

**Issue by fhediger** [google/google-java-format#533]
I use the latest `google-java-format` Intellij plugin based on `google-java-format 1.9`. As I understand it, this version should support Java 14/15 features like switch expressions and text blocks. In our case if any of the mentioned language features are used formatting stops working.

Just wanted to ask whether this may be a bug in my setup or if you're seeing the same problems?

**Intellij IDEA Version:** `Ultimate Edition 2020.2.3 (Build #IU-202.7660.26, built on October 6, 2020)`

**Operating System:** `Ubuntu 20.04.1 LTS`

Here is a small example:

```java
public class FormatTest {
  enum Test {
    A, B
  }
  public static void main(String[] args) {
    String foo =                  "This should not be here";
    Test t = Test.A;
    String foobar = switch(t) {
      case A -> "foobar";
      case B -> "barfoo";
    };
    String xyz = """
            """;
  }
}
```

When I try to format this inside the IDE nothing happens. It shows that it's reformatting the code but the formatting doesn't change.There is no error as far as I can see.

However, formatting it with `google-java-format-1.9-all-deps.jar` it outputs correctly:

```java
public class FormatTest {
  enum Test {
    A,
    B
  }

  public static void main(String[] args) {
    String foo = "This should not be here";
    Test t = Test.A;
    String foobar =
        switch (t) {
          case A -> "foobar";
          case B -> "barfoo";
        };
    String xyz = """
            """;
  }
}
```

Any help concerning this issue would be very much appreciated! Thanks for your great work!

**Comment by lazystone** [comment]
@plumpy seems like #517 didn't fix that?

**Comment by fawind** [comment]
Can report the same (using google-java-format plugin 1.9.0.0 and intellij 2020.2).

I think this is because the default Intellij runtime still uses jdk 11 (at least for 2020.2 and lower). Based on that, the formatter will not load the Java14InputAstVisitor ([code ref](https://github.com/google/google-java-format/blob/93d649d0fbc07fc604f7b47b3098cf6e1df521de/core/src/main/java/com/google/googlejavaformat/java/Formatter.java#L157-L169)).

After manually switching my intellij runtime to one that uses jdk 15 ([following this guide](https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under)), the formatter worked as expected with java 14 language features.

**Comment by rosanas88** [comment]
Thank you @fawind, worked fine here! :)

**Comment by linuswillner** [comment]
@fawind Tried following the guide, but the Choose Runtime approach isn't giving me any success. Did you follow the steps for manually changing your runtime version, or if not, what version of the runtime did you use? 🤔

**Comment by laech** [comment]
As an alternative workaround to changing IntelliJ's runtime JDK version, we can also use IntelliJ's [External Tool](https://www.jetbrains.com/help/idea/configuring-third-party-tools.html) feature to run the formatter as an external command using a different JDK:

![image](https://user-images.githubusercontent.com/66709197/123559877-e214bf00-d7f2-11eb-8669-796c4e7184de.png)

Arguments:

```
-Xmx256m
-XX:TieredStopAtLevel=1
--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
-jar <download-the-latest-all-deps-jar>/google-java-format-1.10.0-all-deps.jar
--replace $FilePath$
```

In the above screenshot, it's configured to use the same JDK as the one used to compile the project to run the formatter (`$JDKPath$`), added `-XX:TieredStopAtLevel=1` too as it seems to make it run quicker for me, since the format process will be short lived.

Then under `Keymap` in IntelliJ's main settings, bind it to a keyboard shortcut to invoke it.

**Comment by chadselph** [comment]
I don't know if this is a stupid question but why should the version of JVM running the formatter be assumed to be the same version as the code it's formatting? Is there something in `Java14InputAstVisitor` that can't run on Java 11? Even if it was behind a flag I don't understand why it shouldn't just load the rules. IntelliJ itself obviously doesn't have this problem.

**Comment by farnots** [comment]
> As an alternative workaround to changing IntelliJ's runtime JDK version, we can also use IntelliJ's [External Tool](https://www.jetbrains.com/help/idea/configuring-third-party-tools.html) feature to run the formatter as an external command using a different JDK:
> 
> <img alt="" width="480" src="https://user-images.githubusercontent.com/66709197/123559877-e214bf00-d7f2-11eb-8669-796c4e7184de.png">
> 
> Arguments:
> 
> ```
> -Xmx256m
> -XX:TieredStopAtLevel=1
> --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
> --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED
> --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED
> --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED
> --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
> -jar <download-the-latest-all-deps-jar>/google-java-format-1.10.0-all-deps.jar
> --replace $FilePath$
> ```
> 
> In the above screenshot, it's configured to use the same JDK as the one used to compile the project to run the formatter (`$JDKPath$`), added `-XX:TieredStopAtLevel=1` too as it seems to make it run quicker for me, since the format process will be short lived.
> 
> Then under `Keymap` in IntelliJ's main settings, bind it to a keyboard shortcut to invoke it.

Thanks for the external tools, working great.

**Comment by bjrke** [comment]
the same problem occurs if you run the gradle spotless plugin and configure google java format with java 17 source code and gradle using java 11.

**Comment by chadselph** [comment]
@bjrke for some reason intellij does not by default use the project JVM for the build tool; you can set it here https://www.jetbrains.com/help/idea/gradle-settings.html#gradle_jvm

**Comment by lazystone** [comment]
@chadselph I think it's different - for me gradle builds works fine, it's when you try to format code using built-in formatter, then it does not work(probably because IDEA is still on java 11)

**Comment by fawind** [comment]
In our fork of google-java-format, we solved this with the hacky workaround of bootstrapping a new JVM to run the formatter in ([code example](https://github.com/palantir/palantir-java-format/blob/a28899e1a897867c7bdb13015842db4c59e9add2/palantir-java-format-jdk-bootstrap/src/main/java/com/palantir/javaformat/bootstrap/BootstrappingFormatterService.java)). In the Intellij plugin, we retrieve the path of the project JDK and and use this JDK to run the formatter main class. This allows us to also set the additional `--add-export` flags that are now required at runtime for Java 16+ ([ref](https://github.com/google/google-java-format#jdk-16)).

The downside is that it adds some latency to each format action but this has been tolerable so far and unblocks projects that want to use newer language features.

Might be worth considering doing something similar here. Happy to contribute this back if wanted!

**Comment by TimvdLippe** [comment]
Apparently this is tied to the runtime version of IntelliJ itself. According to [this table](https://github.com/JetBrains/JetBrainsRuntime#releases-based-on-jdk-17) starting with version 2022.2 IntelliJ uses JDK 17. Therefore, once you upgrade to that version or newer, I think this issue is resolved?

**Comment by tbroyer** [comment]
Note that you'll have to update IntelliJ's configuration to add custom VM options; see #787

**Comment by plumpy** [comment]
This should be fixed if you use the newest version of the plugin (1.16.0.0) with Intellij 2022.3.
