### ISSUE TITLE
Idea plugin prevents Formatter Control from working

### ISSUE THREAD

**Issue by jlorenzen** [google/google-java-format#624]
Idea Version: 2021.1.3
Gradle Spotless plugin version: 5.14.0
google-java-format plugin version: 1.9.0.1

### Problem

Idea reformats code that has been surrounded with the formatter controls
(ie `@formatter:off` and `@formatter:on`). This only happens with the google-java-format
plugin has been enabled for the project. When it's disabled Idea honors the formatter controls.

### Expectation

When code is surrounded with the formatter controls and the google-java-format plugin is enabled,
the plugin won't reformat the code.

### Steps to reproduce

* Configure the gradle spotless plugin for a project like this:
```
spotless {
    java {
        googleJavaFormat()
        toggleOffOn('@formatter:off', '@formatter:on')
    }
}
```

* Import the Idea google style file along
* Install and enable the google-java-format plugin
* Configure the Formatter Control to use the same keywords so spotless and Idea are in sync:
![Screen Shot 2021-07-13 at 12 37 11 PM](https://user-images.githubusercontent.com/107843/125499472-89a93cf3-b117-471b-a275-d37438b50e2f.png)
* Find a section of code and surround it with `//@formatter:off` and `//@formatter:on` and change the formatting so it doesn't conform with GJF.
* Auto format the file (on a Mac Option+Shift+CMD+L).

**Comment by jlorenzen** [comment]
Related to #137

**Comment by jbduncan** [comment]
Hi @jlorenzen, I'm an ex-maintainer for Spotless and an avid google-java-format user.

The `@formatter:off|on` concept comes from Spotless, not google-java-format, and it's an [explicit goal](https://github.com/google/google-java-format/wiki/FAQ#i-just-need-to-configure-it-a-bit-differently-how) of google-java-format to keep customization to a minimum. So I'm sure that the GJF team won't do anything to ensure that the google-java-format plugin for IDEA, the behaviour of which I think you're seeing, respects `@formatter:off|on` tags like Spotless does.

Sorry to be the bearer of bad news. :(

**Comment by jbduncan** [comment]
If removing the google-java-format plugin for IDEA makes you uncomfortable, you could try raising a feature request against Spotless to introduce a plugin for IDEA that makes its formatter use Spotless instead - there's precedence for this with a [Spotless plugin for VS Code](https://github.com/badsyntax/vscode-spotless-gradle) - or by creating such a plugin yourself.

I realise this isn't the easy answer you were hoping for, but I hope it helps!

**Comment by plumpy** [comment]
Yeah, sorry, since this is a Spotless feature, not a google-java-format feature, it's really really feasible for us to support this. Getting a Spotless plugin is the right way forward for you here, as @jbduncan suggests.

In the meantime, as a workaround, you could [run Spotless as an external tool](https://www.jetbrains.com/help/idea/configuring-third-party-tools.html).

**Comment by jbduncan** [comment]
@plumpy Did you mean to say "infeasible" rather than "feasible", by any chance? Or did I misunderstand your message? :)

@jlorenzen, @plumpy's suggestion sounds like a good first thing to try. But if for whatever reason it doesn't work for you, you can try what I personally do in IDEA:

1. Press <kbd>Ctrl</kbd> + <kbd>Ctrl</kbd>. (So the <kbd>Ctrl</kbd> key twice.)
2. Type `gradle spotlessApply`.
3. Press <kbd>Enter</kbd>.

It's more keystrokes, but it will format your code for you using Spotless.

**Comment by plumpy** [comment]
Oops, yeah, I meant to say "not really feasible" instead of "really really feasible" :grin:
