### ISSUE TITLE
What's the difference between google-java-format plugin and google java style xml file?

### ISSUE THREAD

**Issue by jwcheong0420** [google/google-java-format#695]
Hello,

As far as I know, there are two ways to apply google java style for Intellij
1. Install google-java-format plugin and enable it
2. Download [google style xml file](https://raw.githubusercontent.com/google/styleguide/gh-pages/intellij-java-google-style.xml) and import it into File→Settings→Editor→Code Style

I expected the same result, but the two methods seem to produce different results as follows,
- Location of @Getter when @Getter put on a field
    - Code reformatted with google-java-format plugin(1.13.0.0)
    ```java
    @Getter private final String value;
    ```
    - Code reformatted with imported code style from xml file
    ```java
    @Getter
    private final String value;
    ```

- Indent of @ApiImplicitParams({})
    - Code reformatted with google-java-format plugin(1.13.0.0)
    ```java
    @ApiImplicitParams({
      @ApiImplicitParam(name = "name", value = "user name", dataTypeClass = String.class),
    })
    ```
    - Code reformatted with imported code style from xml file
    ```java
    @ApiImplicitParams({
        @ApiImplicitParam(name = "name", value = "user name", dataTypeClass = String.class),
    })
    ```

- Line wrapping when using stream
    - Code reformatted with google-java-format plugin(1.13.0.0)
    ```java
    @RequiredArgsConstructor
    List<Integer> numbers = Arrays.asList(10, 2, 5, 32, 2, 5, 12, 34);
    List<Integer> results =
        numbers.stream()
            .map(number -> number * number)
            .filter(number -> number < 100)
            .collect(Collectors.toList());
    ```
    - Code reformatted with imported code style from xml file
    ```java
    List<Integer> numbers = Arrays.asList(10, 2, 5, 32, 2, 5, 12, 34);
    List<Integer> results = numbers.stream()
        .map(number -> number * number)
        .filter(number -> number < 100)
        .collect(Collectors.toList());
    ```

Is it right that the results are different?
I think the reformat result by the plugin is consistent with the google java convention.
Why did the reformat result by xml file come out like this?

Any help would be much appreciated. Thanks :)

**Comment by jbduncan** [comment]
@jwcheong0420 Good questions. My understanding is the GJF command line tool, library, and IDE plugins came after the XML file, and that Google made the CLI etc. because Eclipse and IntelliJ weren't flexible enough to meet all the requirements of the [Google Java style guide](https://google.github.io/styleguide/javaguide.html) at the time. And I think this is still the case, so the plugin/library/CLI tool should be preferred.

(This explains to me, for example, why the formatting of `@ApiImplicitParam` in your example differs between the two.)

I can't remember where I learned all this, though. Can someone from the GJF team confirm my understanding?

As for why the output is different for the `@Getter` example, I don't really know why, but [this](https://github.com/google/google-java-format/wiki/FAQ#why-didnt-it-leave-my-perfectly-valid-code-alone) page in the wiki might have the information you're after?

I hope this helps. :)

**Comment by jbduncan** [comment]
I can't explain why the XML files haven't been deprecated. 🤷

**Comment by jovan996** [comment]
Can we use both of these formatters together(google java format and google java style xml file) or one excludes the other

**Comment by kevinb9n** [comment]
I'm actually not aware of who maintains the java-google-style.xml file, but indeed as @jbduncan said, this entire formatter exists because the ability of existing tools to format code well is too limited no matter *how* they're configured.

The one thing you do need it for is to handle import sorting, because the GJF IntelliJ plugin only takes over the "format code" function not "optimize imports".

**Comment by timo-abele** [comment]
> The one thing you do need it for is to handle import sorting, because the GJF IntelliJ plugin only takes over the "format code" function not "optimize imports".

As of 2023-03-03 (4f5ffd0) this seems to no longer be the case:

> When enabled, it will replace the normal `Reformat Code` and `Optimize Imports` actions.

https://github.com/google/google-java-format?tab=readme-ov-file#intellij-android-studio-and-other-jetbrains-ides
