### ISSUE TITLE
Re-flow /* */ comment blocks, including Javadoc

### ISSUE THREAD

**Issue by kevinb9n** [google/google-java-format#7]
This is all intentionally disabled for now, but we should consider a project to outfit the formatter with a real Javadoc parser and let it fix up many aspects of Javadoc layout.  And re-flow plain comments (only for /*, not groups of //).

Note that there is some amount of actual *controversy* about whether it should do this, so we should address that before doing too much work.

**Comment by cpovirk** [comment]
I just spent some time reformatting some of Guava's packages' Javadoc to 100 characters, partially using the Eclipse formatter and partially using Vim `gq`. Here are a bunch of notes -- no doubt too many to digest easily but not nearly enough to fully specify behavior :)

- [Indent continued `@tag` lines 4 spaces](https://google.github.io/styleguide/javaguide.html#s7.1.3-javadoc-at-clauses) (or more, but we don't do "align with something on previous line" in code, so I don't see why we would do it here... though Eclipse does).
- [Paragraphs have a "blank" line before them and no space between `<p>` and the following text.](https://google.github.io/styleguide/javaguide.html#s7.1.2-javadoc-paragraphs).
- Presumably `<li>` tags likewise have no space between them and the following text, but presumably they do not have a blank line before. Would we actually remove such a line if it were present?
- Do we have any interest in [reordering `@tags`](https://google.github.io/styleguide/javaguide.html#s7.1.3-javadoc-at-clauses), or does that go beyond our "only whitespace" policy? (Well, I guess that our policy will have to be "only whitespace and asterisks.")
- Don't touch anything inside `<pre>`. It might be code, or it might be fixed-width pseudo-tables or ASCII-art diagrams.
- Possibly don't even insert a newline before `<pre>`, since Guava [likes to put it on the line with the preceding text](https://github.com/google/guava/blob/08a6bb421f0931cc4cee499a631c651e4633787e/guava/src/com/google/common/collect/ImmutableList.java#L614). But I think that pattern can work fine with a newline (or two) before `<pre>`, so we'll have to decide if it's worth a special case or not. Would we actually want to remove the newlines if they were already there?
- Move text off the `/**` and `*/` lines [unless it is a one-liner](https://google.github.io/styleguide/javaguide.html#s7.1.1-javadoc-multi-line).
- Presumably we want to do something for other weird cases like *actual* blank lines (no asterisk) and otherwise non-asterisked lines. Do we treat them as empty but asterisked, I guess? If they're inside a `<pre>`, we would ideally assume that they are otherwise aligned properly. But maybe we don't need to work that hard for an "error" case.
- Do we already look for blank lines between Javadoc and the following methods/field/whatever? I guess I could check this myself.
- This seems "obvious," but the Eclipse formatter mangles it: Keep punctuation (`).,`) and HTML tags attached to the previous word (if they were already and maybe maybe maybe even if not), rather than pushing them to the following line. Otherwise, the line break shows up as a space before the punctuation or at the end of the link. Do the same for attaching HTML tags (and maybe punctuation?) to the *following* word for the same reason. This can result in very long lines in the case of `<a href="...">foo</a>`, since the only natural break is before `href`. If this upsets us, we can break between `"..."` and `>foo`. This works, but people may find it weird. And we'd want the formatter to be smart enough to remove that break when it's no longer necessary.
- [We can break inside `@link` and `@code](http://go/java-practices/javadoc#formatting_general). Eclipse doesn't, though, at least under some circumstances. Maybe it will break in `@linkplain` but not those two? I forget. I don't know if there's any value in following Eclipse in this small way, since we're going to deviate from it in many others, but we could consider that. TODO: Check where within the method/class/field name it is valid to break inside `@link`. Is it only places where you would "normally" put a space, like between method parameters? Can you even do that, or are breaks permitted only in the following free-form text?
- It would probably be nice to put `<!-- MOE:begin_intracomment_strip -->` and `<!-- MOE:end_intracomment_strip -->` each on a separate line. Maybe we can generalize this to do that with all HTML comments? Do HTML comments have other use cases in Javadoc?
- Do we want to do any indentation with `<li>`? Some people seem to like this:
  ```
  <ul>
  <li>Blah blah blah blah blah
      blah blah blah.
  <li>Foo bar baz
  </ul>
  ```
  Possibly this gets more compelling once you have nested lists. Above I've indented 4 spaces, which is nice because of the alignment with the text after the `<li>`. Are there other tags "like this?" If so, 4 spaces might not be as perfect for them, but it's probably good enough -- if we want to do this indentation at all. And things may get weird if the list occurs inside a `@param` tag or something. (Guava does this at least once IIRC.)
- Should we leave double line breaks (i.e., a "blank" line) alone, even if they don't have a `<p>` tag or a `<pre>` tag to justify keeping them apart? Presumably we want to do this in `/* */` comment blocks, but is it the right thing for Javadoc, since the text will all get smooshed together in one paragraph? But it may be annoying for people who are just writing Javadoc for private methods out of the goodness of their hearts and who are now seeing that Javadoc mangled by us because they didn't go to the greater trouble of writing `<p>` every so often. But maybe it's still a net win because it calls people's attention to broken "real" Javadoc? Alternatively, we could insert a `<p>` tag for them.... (We can at least remove blank lines at the top and bottom of the Javadoc, I think.)
- Should we take a position on the number of spaces after a period? I think I've heard that two is "right" for monospace, and it looks like one in HTML, anyway. But most people seem to use one, as does Eclipse (at least in Google's configuration, IIRC).
- We presumably don't want to [remove an initial `<p>` tag](https://google.github.io/styleguide/javaguide.html#s7.1.2-javadoc-paragraphs), but we could. (My presumption here and in some other items is based somewhat on the "only whitespace" policy. But I don't really have an opinion about whether we should follow that policy for Javadoc or not.)
- We presumably don't want to [remove optional closing tags (`</p>`, `</li>`)](http://go/java-practices/javadoc#formatting_general), but we could.
- We presumably don't want to [change `<strong>`, `<em>` to `<b>`, `<i>`](http://go/java-practices/javadoc#formatting_general), but we could.

**Comment by cpovirk** [comment]
Here's a weird edge case around MOE directives and `@tag` sections.

Assuming that we put MOE directives on their own line, some Guava code would look like this:

```
   * @throws IllegalArgumentException if blah blah blah
   *     blah blah
   *     <!-- MOE:begin_intracomment_strip -->
   * @deprecated Internal users should use {@link #foo}
   *     instead because of such and such
   *     <!-- MOE:end_intracomment_strip -->
```

It might be better to have:

```
   * @throws IllegalArgumentException if blah blah blah
   *     blah blah
   * <!-- MOE:begin_intracomment_strip -->
   * @deprecated Internal users should use {@link #foo}
   *     instead because of such and such
   * <!-- MOE:end_intracomment_strip -->
```

Maybe?

If so, what's the rule here? It's probably not "put MOE directives at the beginning of the line always" because we might be MOE-stripping part of a `@tag` section. It might be "put MOE directives at the beginning of the line if they are the last thing in a `@tag` section" (since that means they're really supposed to be "between tags" or "after all tags").

I guess there's a separate case here in which the stripped `@tag` section is the *first* `@tag` section. Then our formatter would presumably want to put a blank line between the MOE directive and the `@tag` section. We'd need another special case here.

(This may all amount to "It's not worth doing anything special for MOE directives....)

**Comment by cpovirk** [comment]
More about the difficulty of handling MOE directives: Sometimes we use them in implementation comments, in which case we won't have HTML comments around them:

       * MOE:begin_intracomment_strip
       * For more information, see http://b/12345
       * MOE:end_intracomment_strip

So we can't just say "We don't need special handling for MOE directives because it's covered entirely by special handling we could add for comments." Well, I mean, we *could*. The above case probably isn't *common*. But it does come up. We could tell those users to switch to `//` comments, though that would be awkward if the stripping occurs in the middle of a larger block comment.

**Comment by cpovirk** [comment]
I overstated how bad it is to split after some HTML tags:

```
  /**
   * foo bar <a href="...">
   * baz</a> blah blah blah.
   */
```

I thought that this would produce a link whose first character is a space. But that's wrong: Because there's already a space before the `<a>` tag, the space after the `<a>` tag is ignored.

I still thought that I had seen problems with this pattern before, but it may have been in only a minority of cases, presumably those in which the `<a>` tag followed a non-space character (say, `non-<a href="...">serializable</a>`).

**Comment by cpovirk** [comment]
It would be a little sad if the formatter did things like this:

```
/**
 * foo bar baz {@code 1 2 3 4 5
 * 6}. blah blah
 */
```

It might be nicer to keep the `{@code}` block all together -- or perhaps even to split it more "evenly."

Similarly at the sentence level, some people prefer...

```
/**
 * Here is one sentence.
 * Here is another.
 */
```

...over...

```
/**
 * Here is one sentence. Here
 * is another.
 */
```

This probably gets into "widows" and "orphans" and "TeX" and all that, though, which is probably a significant complication over what naive word wrapping does. My guess is that it won't be worth it and that this will be a case in which we need to revert the formatter's work if we really want the old version.

**Comment by jrtom** [comment]
My suggestion for the "period at the end of the line" is just to not reflow that text, i.e., assume that the author wanted it that way.  (I may be biased here, because I often flow my text that way to make it easier to read _as source code_.)

**Comment by cpovirk** [comment]
My fear is that things will get stuck that way unintentionally.

```
/**
 * This is the first sentence. This is the second, which is a longer sentence
 * then the first. This is the third. This is the fourth.
 */
```

Now I remove the second sentence, and the formatter is stuck at...

```
/**
 * This is the first sentence.
 * This is the third. This is the fourth.
 */
```

...instead of rewriting to...

```
/**
 * This is the first sentence. This is the third. This is the fourth.
 */
```

(Maybe the particular case above is detectable, since entire new sentences can fit on the line now. Or maybe we can apply a rule that, if the break is "close enough" to 100 characters, we leave it alone (though I personally just prefer to wrap).)

Of course it's easy to manually join the lines and reformat. Alternatively, it's easy to manually *split* the lines and reformat... assuming that we allow you to reformat only part of a comment, which we might well not (or might not have an easy UI for). So there's that :(

To present a false dichotomy:

- Line breaking in comment paragraph source code is very important. Let's make the formatter do the right thing with one of those fancy text layout algorithms -- fully automatic so that programmers don't need to worry about it.
- Line breaking in comment paragraph source code is somewhat important but not important enough to introduce potentially surprising or frustrating behavior over -- better to encourage users to accept the default formatting to save time rather than tweaking line breaks each time they edit a section of docs.

I lean somewhat toward the second option, but really my primary goal is not to have to hand-tweak formatter output if I touch one of the specially wrapped comments :)

(Obviously an alternative solution to that is to get over my own twitchiness over "unnecessary" ragged lines. But what fun would that be?)

**Comment by jrtom** [comment]
Your example does not apply to the rule I suggested: in that case there is no existing period at the end of the (first) line (PATEOTL) to preserve.  :)

That said, it would apply to this example:

```
/**
 * This is the first sentence.  This is the second and longer sentence.
 * This is the third sentence.
 */
```

One way to resolve this: if you have a PATEOTL, don't reflow text on that line _unless it is already being edited_.  In this case, if you remove the "second and longer sentence", you'd move "This is the third sentence" up, but not otherwise.

(And yes, another way would be for you to stop worrying about ragged lines so much.  ;) )

**Comment by cpovirk** [comment]
There is no existing period at the end of the first line originally, but there is when the formatter is run, right?

**Comment by jrtom** [comment]
I was thinking in terms of auto-running the formatter in the context of a changelist, I guess.  :/

I'm going to retreat to my previously prepared position of "stop worrying about ragged lines so much" (specifically in the context of having a period at the end of a line).  :)

**Comment by cpovirk** [comment]
- Don't line break before a `@` character, since it will then be interpreted as a tag. Alternatively, change it to `&#64;` (but probably just avoid the break).

**Comment by cpovirk** [comment]
- In an ideal world, recognize existing mistaken breaks before `@`. "Mistaken" could be defined in a number of ways:
  - A block tag inside an inline tag like `{@code}`
  - A block tag without a recognized name. (But it might be a custom Javadoc tag.)
  - A block tag that begins with a capital letter, presumably intended as an annotation. (It *still* might be a custom Javadoc tag, but this at least seems less likely.)
  - A block tag that is literally `@Override` or another common class name. We might also include `@Foo` when `Foo` is imported or declared in the file. (In theory this could still catch custom Javadoc tags, but the possibility seems remote.)
  - Some kind of heuristic that looks at the remaining lines of Javadoc.

**Comment by cpovirk** [comment]
- A block tag that's indented.
