### ISSUE TITLE
Cannot open Java sources if NetBeans 12.6 is run on JDK 1.8.0_271

### ISSUE THREAD

**Issue by jkovalsky** [google/google-java-format#703]
I tried to install 1.14.2 version of [External Java Code Formatters](https://plugins.netbeans.apache.org/catalogue/?id=15) plugin to my Apache NetBeans IDE 12.6 running on JDK 1.8.0 Update 271 but it resulted in unusable Editor. Opening any Java file resulted in empty editor due to attached [UCVError.txt](https://github.com/google/google-java-format/files/7807769/UCVError.txt). Please see the attached file. Can you please compile the plugin with older JDK?

**Comment by funfried** [comment]
@jkovalsky This is not my repository, this is the repository of the Google Formatter. Are you sure you wanted to file this issue here? Maybe you were looking for [this page](https://github.com/funfried/externalcodeformatter_for_netbeans/)
I stopped supporting Java 1.8.0 as a runtime Java version which is documented in the plugin. But this was quite some time ago. Is supporting Java 1.8.0 still mandatory?

**Comment by tbroyer** [comment]
Note however that Google Java Format itself requires JDK 11 since version 1.8: https://github.com/google/google-java-format/releases/tag/google-java-format-1.8

**Comment by jkovalsky** [comment]
Oh, I apologize. I wanted to file an issue about missing JDK 8 support so went to [Known Issues](https://funfried.github.io/externalcodeformatter_for_netbeans/known_issues.html) page where I saw a link to some issue so without much reading I got here.

However, as download page for [NetBeans 12.6](https://netbeans.apache.org/download/nb126/nb126.html) says the IDE runs also on JDK 8 so I will file this bug in the [other repository](https://github.com/funfried/externalcodeformatter_for_netbeans/).

**Comment by jkovalsky** [comment]
For the reference: https://github.com/funfried/externalcodeformatter_for_netbeans/issues/178
