### ISSUE TITLE
Unused static import not removed

### ISSUE THREAD

**Issue by gabrielittner** [google/google-java-format#72]
Running google-java-format didn't remove this unused import `import static java.util.stream.Collectors.toList`. In that class a different non-static `toList()` method was used.  After removing the usages of the other toList the unused import was removed by google-java-format.

**Comment by gabrielittner** [comment]
It also doesn't remove unused static imports of enum values that are only used in a switch statement.
```
import static java.time.DayOfWeek.MONDAY; //unused
import static java.time.DayOfWeek.TUESDAY; //unused
//...

switch (day) {
    case MONDAY:
    case TUESDAY:
    //...
}
```

**Comment by cushon** [comment]
google-java-format's import fixing is best effort. It only has access to the syntax of an individual file, these cases aren't possible without compiling the code to e.g. figure out which overload of `toList` is used, and determine that `MONDAY` and `TUESDAY` are enum constants rather than constant fields.

**Comment by Fernal73** [comment]
Static star imports are not removed either. Thanks for the explanation provided.
