### ISSUE TITLE
Release native builds

### ISSUE THREAD

**Issue by dlicois** [google/google-java-format#868]
Hello

GraalVM native-image support appears to have been added a little while ago https://github.com/google/google-java-format/pull/728 (see also https://github.com/google/google-java-format/issues/358). However there are no official native build release on the release page https://github.com/google/google-java-format/releases. is it working ?

Providing these could greatly benefit to java tooling as it would allow fast formatting without having to rely on IDEs customization and while being fully compliant with google style guide. This could be easily imported in Visual Studio Code for example.

Platform targets of most interest would be win32-x64, linux-x64, darwin-x64, darwin-arm64.

**Comment by vorburger** [comment]
Yeah, this would be nice. 

Especially as there are now people who distribute native builds themselves elsewhere.

Before thinking "release", there should probably be a way to (easily) build it here in this project? 

So #894 would probably be a pre-requisite here.

**Comment by vorburger** [comment]
My #1045 will (should, to be tested and confirmed) make a native builds available at the next release cycle!

**Comment by vorburger** [comment]
As (sorry for cross posting, I'm just excited).

FYI https://github.com/JoseVSeb/google-java-format-for-vs-code/issues/17 with links to my posts about this:

* https://tooting.ch/@vorburger/111952897874900517
* https://bsky.app/profile/vorburger.ch/post/3klp4ip2yqc2k
* https://twitter.com/vorburger/status/1759220021568340105

_"Formatting completed in 45ms."_ instead of 473ms previously...

That x10 is actually noticeable on Ctrl-S Save a *.java, even on a fast computer - very cool!

@cushon close this issue?

**Comment by natros** [comment]
You can get better results if you compile with profile-guided optimizations (PGO)

**Comment by vorburger** [comment]
> You can get better results if you compile with profile-guided optimizations (PGO)

@natros we welcome your PR to the configuration that's [here](https://github.com/google/google-java-format/blob/92c609a43bc894e4cd69e9c037491163303d97ed/core/pom.xml#L308) if you have expertise in this and would like to contribute that!

**Comment by cushon** [comment]
I'm going to close this out for now, PGO sounds worth considering as a follow-up.
